#
# GitHub Actions Workflow
#   reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#

name: "Build and Test"

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
  run:
    # When Bash is specified explicitly, a different command is run internally by GH:
    # shell: unspecified => bash -e {0}
    # shell: bash => bash --noprofile --norc -eo pipefail {0} <-- Note that this enables the useful pipefail option.
    # see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  build:
    name: "Build (${{ matrix.preset }})"

    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [ macos-latest ]
        preset: [ stm32h533-debug, stm32h533-release ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Python currently not needed
      # - name: Setup Python
      #   # https://github.com/actions/setup-python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'

      # Rust and CMake are already installed in the macos-12 runner
      # see https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

      - name: Upgrade Bash on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install bash

      - name: Install Arm GNU Toolchain using brew
        if: startsWith(matrix.os, 'macos')
        run: brew install --cask gcc-arm-embedded

      - name: Configue project
        id: configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        id: build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Upload build outputs
        if: always()
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-${{ matrix.os }}-${{ matrix.preset }}
          path: |
            build/${{ matrix.preset }}/targets/*/lionkey_*.bin
            build/${{ matrix.preset }}/targets/*/lionkey_*.hex
            build/${{ matrix.preset }}/targets/*/lionkey_*.elf
            build/${{ matrix.preset }}/targets/*/lionkey_*.map

  test:
    name: "Unit tests on host"

    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [ macos-latest, ubuntu-latest ]
        preset: [ host-debug ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Upgrade Bash on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install bash

      - name: Configue project
        id: configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        id: build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Create log dir for test outputs
        id: test-dir
        run: mkdir -p log

      - name: Test
        id: test
        run: ctest --extra-verbose --test-dir build/${{ matrix.preset }} |& tee log/ctest-output.txt

      - name: Upload test outputs
        if: always()
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs-${{ matrix.os }}-${{ matrix.preset }}
          path: |
            log/
            build/${{ matrix.preset }}/
